from __future__ import annotations

# Maps each universe ticker to its sector name and parent sector ETF.
# Extend this dict as the universe grows.
SECTOR_MAP: dict[str, dict[str, str]] = {
    # Technology — XLK
    "AAPL": {"sector": "Technology", "etf": "XLK"},
    "MSFT": {"sector": "Technology", "etf": "XLK"},
    "NVDA": {"sector": "Technology", "etf": "XLK"},
    "AMD": {"sector": "Technology", "etf": "XLK"},
    "GOOGL": {"sector": "Technology", "etf": "XLK"},
    "GOOG": {"sector": "Technology", "etf": "XLK"},
    "META": {"sector": "Technology", "etf": "XLK"},
    "ORCL": {"sector": "Technology", "etf": "XLK"},
    "CRM": {"sector": "Technology", "etf": "XLK"},
    "ADBE": {"sector": "Technology", "etf": "XLK"},
    "INTC": {"sector": "Technology", "etf": "XLK"},
    "QCOM": {"sector": "Technology", "etf": "XLK"},
    "TXN": {"sector": "Technology", "etf": "XLK"},
    "ANET": {"sector": "Technology", "etf": "XLK"},
    "GTLB": {"sector": "Technology", "etf": "XLK"},
    "ZETA": {"sector": "Technology", "etf": "XLK"},
    "SNOW": {"sector": "Technology", "etf": "XLK"},
    "DDOG": {"sector": "Technology", "etf": "XLK"},
    "MDB": {"sector": "Technology", "etf": "XLK"},
    "NET": {"sector": "Technology", "etf": "XLK"},
    "CRWD": {"sector": "Technology", "etf": "XLK"},
    "PANW": {"sector": "Technology", "etf": "XLK"},
    "FTNT": {"sector": "Technology", "etf": "XLK"},
    "CYBR": {"sector": "Technology", "etf": "XLK"},
    "ZS": {"sector": "Technology", "etf": "XLK"},
    "S": {"sector": "Technology", "etf": "XLK"},
    "OKTA": {"sector": "Technology", "etf": "XLK"},
    "NOW": {"sector": "Technology", "etf": "XLK"},
    "WDAY": {"sector": "Technology", "etf": "XLK"},
    "INTU": {"sector": "Technology", "etf": "XLK"},
    "SHOP": {"sector": "Technology", "etf": "XLK"},
    "TWLO": {"sector": "Technology", "etf": "XLK"},
    "ZI": {"sector": "Technology", "etf": "XLK"},
    "BILL": {"sector": "Technology", "etf": "XLK"},
    "HUBS": {"sector": "Technology", "etf": "XLK"},
    "SMAR": {"sector": "Technology", "etf": "XLK"},
    # Communication Services — XLC
    "NFLX": {"sector": "Communication Services", "etf": "XLC"},
    "DIS": {"sector": "Communication Services", "etf": "XLC"},
    "T": {"sector": "Communication Services", "etf": "XLC"},
    "VZ": {"sector": "Communication Services", "etf": "XLC"},
    "TMUS": {"sector": "Communication Services", "etf": "XLC"},
    "LYFT": {"sector": "Communication Services", "etf": "XLC"},
    "UBER": {"sector": "Communication Services", "etf": "XLC"},
    "SNAP": {"sector": "Communication Services", "etf": "XLC"},
    "PINS": {"sector": "Communication Services", "etf": "XLC"},
    "RBLX": {"sector": "Communication Services", "etf": "XLC"},
    "EBAY": {"sector": "Communication Services", "etf": "XLC"},
    "ETSY": {"sector": "Communication Services", "etf": "XLC"},
    # Consumer Discretionary — XLY
    "AMZN": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "TSLA": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "HD": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "LOW": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "NKE": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "MCD": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "SBUX": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "TGT": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "BKNG": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "MAR": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "HLT": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "RCL": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "CCL": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "ABNB": {"sector": "Consumer Discretionary", "etf": "XLY"},
    # Consumer Staples — XLP
    "PG": {"sector": "Consumer Staples", "etf": "XLP"},
    "KO": {"sector": "Consumer Staples", "etf": "XLP"},
    "PEP": {"sector": "Consumer Staples", "etf": "XLP"},
    "COST": {"sector": "Consumer Staples", "etf": "XLP"},
    "WMT": {"sector": "Consumer Staples", "etf": "XLP"},
    "CVS": {"sector": "Consumer Staples", "etf": "XLP"},
    "WBA": {"sector": "Consumer Staples", "etf": "XLP"},
    "MO": {"sector": "Consumer Staples", "etf": "XLP"},
    "PM": {"sector": "Consumer Staples", "etf": "XLP"},
    # Healthcare — XLV
    "JNJ": {"sector": "Healthcare", "etf": "XLV"},
    "UNH": {"sector": "Healthcare", "etf": "XLV"},
    "PFE": {"sector": "Healthcare", "etf": "XLV"},
    "MRK": {"sector": "Healthcare", "etf": "XLV"},
    "ABBV": {"sector": "Healthcare", "etf": "XLV"},
    "LLY": {"sector": "Healthcare", "etf": "XLV"},
    "BMY": {"sector": "Healthcare", "etf": "XLV"},
    "AMGN": {"sector": "Healthcare", "etf": "XLV"},
    "GILD": {"sector": "Healthcare", "etf": "XLV"},
    "REGN": {"sector": "Healthcare", "etf": "XLV"},
    "VRTX": {"sector": "Healthcare", "etf": "XLV"},
    "BIIB": {"sector": "Healthcare", "etf": "XLV"},
    "MRNA": {"sector": "Healthcare", "etf": "XLV"},
    "ISRG": {"sector": "Healthcare", "etf": "XLV"},
    "DHR": {"sector": "Healthcare", "etf": "XLV"},
    "ABT": {"sector": "Healthcare", "etf": "XLV"},
    "TMO": {"sector": "Healthcare", "etf": "XLV"},
    "MDT": {"sector": "Healthcare", "etf": "XLV"},
    "SYK": {"sector": "Healthcare", "etf": "XLV"},
    "ZBH": {"sector": "Healthcare", "etf": "XLV"},
    # Financials — XLF
    "JPM": {"sector": "Financials", "etf": "XLF"},
    "BAC": {"sector": "Financials", "etf": "XLF"},
    "WFC": {"sector": "Financials", "etf": "XLF"},
    "GS": {"sector": "Financials", "etf": "XLF"},
    "MS": {"sector": "Financials", "etf": "XLF"},
    "C": {"sector": "Financials", "etf": "XLF"},
    "AXP": {"sector": "Financials", "etf": "XLF"},
    "V": {"sector": "Financials", "etf": "XLF"},
    "MA": {"sector": "Financials", "etf": "XLF"},
    "PYPL": {"sector": "Financials", "etf": "XLF"},
    "SQ": {"sector": "Financials", "etf": "XLF"},
    "AFRM": {"sector": "Financials", "etf": "XLF"},
    "SOFI": {"sector": "Financials", "etf": "XLF"},
    "HOOD": {"sector": "Financials", "etf": "XLF"},
    "COF": {"sector": "Financials", "etf": "XLF"},
    "USB": {"sector": "Financials", "etf": "XLF"},
    "PNC": {"sector": "Financials", "etf": "XLF"},
    "BLK": {"sector": "Financials", "etf": "XLF"},
    "SCHW": {"sector": "Financials", "etf": "XLF"},
    "ICE": {"sector": "Financials", "etf": "XLF"},
    "CME": {"sector": "Financials", "etf": "XLF"},
    # Energy — XLE
    "XOM": {"sector": "Energy", "etf": "XLE"},
    "CVX": {"sector": "Energy", "etf": "XLE"},
    "COP": {"sector": "Energy", "etf": "XLE"},
    "EOG": {"sector": "Energy", "etf": "XLE"},
    "SLB": {"sector": "Energy", "etf": "XLE"},
    "OXY": {"sector": "Energy", "etf": "XLE"},
    "MPC": {"sector": "Energy", "etf": "XLE"},
    "VLO": {"sector": "Energy", "etf": "XLE"},
    "PSX": {"sector": "Energy", "etf": "XLE"},
    "BKR": {"sector": "Energy", "etf": "XLE"},
    "KMI": {"sector": "Energy", "etf": "XLE"},
    "WMB": {"sector": "Energy", "etf": "XLE"},
    "OKE": {"sector": "Energy", "etf": "XLE"},
    "ET": {"sector": "Energy", "etf": "XLE"},
    # Industrials — XLI
    "GE": {"sector": "Industrials", "etf": "XLI"},
    "HON": {"sector": "Industrials", "etf": "XLI"},
    "CAT": {"sector": "Industrials", "etf": "XLI"},
    "DE": {"sector": "Industrials", "etf": "XLI"},
    "RTX": {"sector": "Industrials", "etf": "XLI"},
    "LMT": {"sector": "Industrials", "etf": "XLI"},
    "NOC": {"sector": "Industrials", "etf": "XLI"},
    "BA": {"sector": "Industrials", "etf": "XLI"},
    "UPS": {"sector": "Industrials", "etf": "XLI"},
    "FDX": {"sector": "Industrials", "etf": "XLI"},
    "CSX": {"sector": "Industrials", "etf": "XLI"},
    "NSC": {"sector": "Industrials", "etf": "XLI"},
    "DAL": {"sector": "Industrials", "etf": "XLI"},
    "UAL": {"sector": "Industrials", "etf": "XLI"},
    "AAL": {"sector": "Industrials", "etf": "XLI"},
    "WM": {"sector": "Industrials", "etf": "XLI"},
    "RSG": {"sector": "Industrials", "etf": "XLI"},
    # Materials — XLB
    "LIN": {"sector": "Materials", "etf": "XLB"},
    "APD": {"sector": "Materials", "etf": "XLB"},
    "ECL": {"sector": "Materials", "etf": "XLB"},
    "SHW": {"sector": "Materials", "etf": "XLB"},
    "NEM": {"sector": "Materials", "etf": "XLB"},
    "FCX": {"sector": "Materials", "etf": "XLB"},
    "AA": {"sector": "Materials", "etf": "XLB"},
    "X": {"sector": "Materials", "etf": "XLB"},
    "NUE": {"sector": "Materials", "etf": "XLB"},
    # Real Estate — XLRE
    "AMT": {"sector": "Real Estate", "etf": "XLRE"},
    "PLD": {"sector": "Real Estate", "etf": "XLRE"},
    "CCI": {"sector": "Real Estate", "etf": "XLRE"},
    "EQIX": {"sector": "Real Estate", "etf": "XLRE"},
    "WELL": {"sector": "Real Estate", "etf": "XLRE"},
    # Utilities — XLU
    "NEE": {"sector": "Utilities", "etf": "XLU"},
    "DUK": {"sector": "Utilities", "etf": "XLU"},
    "SO": {"sector": "Utilities", "etf": "XLU"},
    "D": {"sector": "Utilities", "etf": "XLU"},
    "AEP": {"sector": "Utilities", "etf": "XLU"},
    "XEL": {"sector": "Utilities", "etf": "XLU"},
    "EXC": {"sector": "Utilities", "etf": "XLU"},
    "PCG": {"sector": "Utilities", "etf": "XLU"},
    "ED": {"sector": "Utilities", "etf": "XLU"},
    # Sector ETFs (self-referencing for bridge ETF snapshot)
    "XLK": {"sector": "Technology", "etf": "XLK"},
    "XLE": {"sector": "Energy", "etf": "XLE"},
    "XLV": {"sector": "Healthcare", "etf": "XLV"},
    "XLU": {"sector": "Utilities", "etf": "XLU"},
    "XLI": {"sector": "Industrials", "etf": "XLI"},
    "XLF": {"sector": "Financials", "etf": "XLF"},
    "XLP": {"sector": "Consumer Staples", "etf": "XLP"},
    "XLY": {"sector": "Consumer Discretionary", "etf": "XLY"},
    "XLB": {"sector": "Materials", "etf": "XLB"},
    "XLRE": {"sector": "Real Estate", "etf": "XLRE"},
    "XLC": {"sector": "Communication Services", "etf": "XLC"},
    # Benchmarks / broad market
    "SPY": {"sector": "Benchmark", "etf": "SPY"},
    "QQQ": {"sector": "Benchmark", "etf": "QQQ"},
    "IWM": {"sector": "Benchmark", "etf": "IWM"},
    "DIA": {"sector": "Benchmark", "etf": "DIA"},
}


def get_sector(ticker: str) -> str:
    """Return sector name for ticker, or 'Unknown' if not in map."""
    return SECTOR_MAP.get(ticker, {}).get("sector", "Unknown")


def get_etf(ticker: str) -> str:
    """Return parent sector ETF for ticker, or '' if not in map."""
    return SECTOR_MAP.get(ticker, {}).get("etf", "")
