"use client"

import { useMemo } from "react"
import { useCockpit } from "@/lib/hooks"
import { ViewHeader, Kpis, Panel } from "./shared"

/** After-close review — derived from the cockpit read model. */
export function ReviewView() {
  const { data } = useCockpit()
  const rows = data?.rows ?? []
  const stats = useMemo(() => {
    const triggered = rows.filter((r) => r.entry_triggered || r.status === "triggered")
    const winners = triggered.filter((r) => (r.research_unrealized_pl_pct ?? 0) > 0).length
    const losers = triggered.filter((r) => (r.research_unrealized_pl_pct ?? 0) < 0).length
    return { triggered: triggered.length, winners, losers, watching: rows.filter((r) => r.status === "watching").length }
  }, [rows])

  return (
    <div>
      <ViewHeader title="After Close · Review" sub={data?.generated_at ?? "session recap"} />
      <Kpis
        items={[
          { label: "Triggered", value: stats.triggered },
          { label: "In profit", value: stats.winners, tone: "pos" },
          { label: "In loss", value: stats.losers, tone: "neg" },
          { label: "Still watching", value: stats.watching },
        ]}
      />
      <Panel title="Session notes">
        <p className="text-mut" style={{ fontSize: 12, lineHeight: 1.6 }}>
          {stats.triggered === 0
            ? "No entries triggered this session — the scanner stayed in watch mode."
            : `${stats.triggered} name(s) triggered; ${stats.winners} green, ${stats.losers} red on live mark. Full EOD recap is generated by the after-market-review pipeline.`}
        </p>
      </Panel>
    </div>
  )
}
